---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  Test: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-OneTimeURL
no_index:
  directory:
    - t
    - inc
requires:
  Apache: 0
  DB_File: 0
  Digest::MD5: 0
  MLDBM: 0
  Mail::Send: 0
  perl: 5.006
resources:
  repository: git://github.com/neilbowers/Apache-OneTimeURL.git
version: 1.32
